### ISSUE TITLE
evaluation OS for Nios II

### ISSUE THREAD

**Issue by fl-la** [Alabamajack/Garfield#2]
- [x] FreeRTOS
- [x] Erika OSEK

**Comment by Litschi** [comment]
https://sudani93.wordpress.com/2015/11/11/running-freertos-on-nios-ii/

**Comment by Litschi** [comment]
http://download.tuxfamily.org/erika/webdownload/manuals_pdf/arch_nios2_1_2_3.pdf
http://erika.tuxfamily.org/wiki/index.php?title=Altera_Nios_II
http://download.tuxfamily.org/erika/webdownload/manuals_pdf/arch_nios2_api_tutorial_1_0_6.pdf
