### ISSUE TITLE
Clientside Software

### ISSUE THREAD

**Issue by fl-la** [Alabamajack/Garfield#25]
- [ ] Software for visualization of Garfield Data like:
   * [ ] speed
   * [ ] acceleration ( maybe mpu, rotary encoder)

- [ ] Sofware to send data to Garfield like :
   * [ ] steering angle between 0 - 180°
   * [ ] speed between 0 and 100 %
   * [ ] Direction
   * [ ] lighting (front/back)

**Comment by Philipp-E** [comment]
- [ ] More Data to send from Clientside Data:
    - [ ] Direction (forward, backwards)
