### ISSUE TITLE
Schematic - Servo In

### ISSUE THREAD

**Issue by fl-la** [Alabamajack/Garfield#26]
What is the functionality of Label SERVO_IN or what does this?

**Comment by Philipp-E** [comment]
SERVO_IN goes through the levelshifter to the servo for setting the angle of the servo by providing a PWM signal

**Comment by fl-la** [comment]
Servo is a little bit confusing... Why don't call it Steering_Signal or something similar?

**Comment by Philipp-E** [comment]
Good idea, i will change it. 
So then we would have Steering_Signal_IN before the levelshifter and Steering_Signal_OUT after the levelshifter, except you have a better idea for declaring the way of the signal through the levelshifter.

**Comment by fl-la** [comment]
:+1:
