### ISSUE TITLE
Driver for Display

### ISSUE THREAD

**Issue by fl-la** [Alabamajack/Garfield#8]
Writing a driver for the 2.8" TFT Display
don't use touchi

**Comment by Philipp-E** [comment]
Hello world for using Display:

#include "system.h"
#include "Display.hpp"

int main()
{
          Display lcd(240,320);
	  lcd.init(ILI9341_BLACK);
          lcd.writeLine("Hello World!", ILI9341_DARKGREEN, 3);
          lcd.writeLine("Hello World!", ILI9341_DARKGREEN, 2);
          lcd.writeLine("Hello World!", ILI9341_DARKGREEN, 1);

          return 0;
}


This example prints the following in Dark green on black background:

# 1: Hello World!
## 2: Hello World!
3: Hello World!
